### ISSUE TITLE
::pedestal.http/join? option must be default false

### ISSUE THREAD

**Issue by josefigueroa-nedap** [nedap/components.pedestal#15]
## Problem statement

The option `::pedestal.http/join?` tells the web server to block (`true`) or not (`false`) after starting.

If the webserver blocks, any system using the `server` component do not finish the start up, which may mess with any shutdown handler that would use the started system.

Even if we can change this option to `false` in production for all the applications we have, it is quite difficult to detect the shutdown problem if everything seems to work properly after starting the web server.

## Proposal

Set default to `false` the option `::pedestal.http/join?` in the service component.

**Comment by jwkoelewijn** [comment]
I think it should be set to `false`, like it is done in the `dev-map` in https://github.com/nedap/components.pedestal/blob/master/src/nedap/components/pedestal/service/component.clj

**Comment by jwkoelewijn** [comment]
> If false, do *_not_* block the thread that starts the web server. Passed to the container.

Highlighting added my me

**Comment by josefigueroa-nedap** [comment]
I updated the issue. Probably the rage still confusing my head. Thanks JW for the correction 👍
